spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sremi
    username: sremi
    password: sremi
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database: MYSQL
    show-sql: true
    hibernate.ddl-auto: update
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

---
spring:
  profiles: default

invoice:
  archive:
    file:
      path: C:\Dev\archives\invoice\
  certificateNumber: 03/2016
  withVat: true
  vatRate: 20.0

bl:
  archive:
    file:
      path: C:\Dev\archives\bl\
excel:
  file:
    path: C:\Dev\CBSREMI.xls

---
spring:
  profiles: prod